// all possible options will be stored
config = {};
// a unique key that identifies this application - DO NOT LEAVE THIS EMPTY!
config['app_key'] = 'ROPaBJaMHmH37BBTAPbXhQllTrjyQ3awkSIWwSgZQLVMTU3Gu8JqzdQ';
// a secret key to be used during encryption
config['encryption_key'] = '';
// URL running the proxy app
//$config['app_url'] = 'https://www.mysampleproxy.com/proxyfolder/';
/*
how unique is each URL that is generated by this proxy app?
0 - no encoding of any sort. People can link to proxy pages directly: ?q=http://www.yahoo.com
1 - Base64 encoding only, people can hotlink to your proxy
2 - unique to the IP address that generated it. A person that generated that URL, can bookmark it and visit it and any point
3 - unique to that session and IP address - URL no longer valid anywhere when that browser session that generated it ends
*/
config['url_mode'] = 2;
// plugins to load - plugins will be loaded in this exact order as in array
config['plugins'] = {0:'HeaderRewrite',1:'Stream',2:'Cookie',3:'Proxify',4:'UrlForm',5:'Youtube',6:'DailyMotion',7:'RedTube',8:'XHamster',9:'XVideos',10:'Xnxx',11:'Pornhub',12:'Twitter'};
// additional curl options to go with each request
config['curl'] = {};
//$config['replace_title'] = 'Google Search';
//$config['error_redirect'] = "https://unblockvideos.com/#error={error_msg}";
//$config['index_redirect'] = 'https://unblockvideos.com/';
// $config['replace_icon'] = 'icon_url';
// this better be here other Config::load fails
return config;
